import path from 'node:path';
import type { Answers, Clip, Transcript } from './types.js';
import { validateFolder } from './workspace.js';

/** Candidates are copied from the request, never generated by Jev. */
export function namingCandidates(request: string): string[] {
  const values = [...request.matchAll(/["“`]([^"”`]+)["”`]|'([^']+)'/g)].map(match => (match[1] ?? match[2])!);
  for (const match of request.matchAll(/(?=\b(?:into|to|in|called|named|with|suffix|em|para|chamad[ao]|nome|sufixo|com)\s+([^,;!?\n]+))/gi)) {
    const words = match[1]!.split(/\s+(?:and|then|e|depois)\s+/i)[0]!.trim().split(/\s+/);
    for (let n = Math.min(words.length, 5); n > 0; n--) values.push(words.slice(0, n).join(' ').replace(/[.!?]+$/, ''));
  }
  // ponytail: bounded EN/PT candidate finder; unsupported wording falls back to explicit input.
  return [...new Set(values)].filter(value => {
    try { validateFolder(value); return value.length <= 80; } catch { return false; }
  }).slice(0, 40);
}

export function chosenName(answers: Answers, id: string, candidates: string[]): string | undefined {
  const answer = answers[id];
  if (answer?.type !== 'choice' || (answer.probabilities[answer.choice] ?? 0) < 0.8) return undefined;
  const match = /^name_(\d+)$/.exec(answer.choice);
  return match ? candidates[Number(match[1])] : undefined;
}

export function validateStem(stem: string): void {
  validateFolder(stem);
  if (stem.includes('/') || Buffer.byteLength(stem) > 160) throw new Error('Use a filename stem of at most 160 bytes, without folders.');
}

export function transcriptText(transcript: Transcript): string {
  return transcript.text || transcript.words.map(word => word.text).join(' ') || transcript.segments.map(segment => segment.text).join(' ');
}

/** An opening-line label, not a generated summary of the clip. */
export function suggestedStem(clip: Clip, index: number, transcript?: Transcript, base?: string): string {
  const original = path.posix.basename(clip.path, path.posix.extname(clip.path));
  const opening = transcript ? transcriptText(transcript).trim().split(/\s+/).slice(0, 7).join(' ') : '';
  const label = (base ?? (opening || original)).normalize('NFKD').replace(/\p{M}/gu, '')
    .replace(/[^\p{L}\p{N}_-]+/gu, '-').replace(/^-+|-+$/g, '').slice(0, 60).replace(/-+$/, '') || 'clip';
  return `${String(index + 1).padStart(2, '0')}-${label}`;
}
